# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import multiselectfield.db.fields
import hoshimori.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoshimori', '0003_auto_20170720_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponupgrade',
            name='rhythm',
        ),
        migrations.AddField(
            model_name='weaponupgrade',
            name='rhythm_1',
            field=models.PositiveIntegerField(null=True, verbose_name='1 Beat'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='weaponupgrade',
            name='rhythm_2',
            field=models.PositiveIntegerField(null=True, verbose_name='2 Beat'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='weaponupgrade',
            name='rhythm_3',
            field=models.PositiveIntegerField(null=True, verbose_name='3 Beat'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='action_skill_damage',
            field=models.CharField(max_length=200, null=True, verbose_name='Skill Damage'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='action_skill_effects',
            field=models.CharField(max_length=200, null=True, verbose_name='Skill Effect'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='atk_1',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='ATK (Level 1)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='atk_50',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='ATK (Level 50)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='charge_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='Charge comment'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='charge_damage',
            field=models.CharField(max_length=200, null=True, verbose_name='Charge damage'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='charge_hit',
            field=models.CharField(max_length=50, null=True, verbose_name='Charge hits'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='charge_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Charge name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='charge_range',
            field=models.CharField(max_length=300, null=True, verbose_name='Charge range'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='def_1',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='DEF (Level 1)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='def_50',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='DEF (Level 50)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='evolved_action_skill_damage',
            field=models.CharField(max_length=200, null=True, verbose_name='Skill Damage (Evolved)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='evolved_nakayoshi_skill_effect',
            field=models.CharField(max_length=200, null=True, verbose_name='Passive Skill Effect (Evolved)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='evolved_nakayoshi_skill_target',
            field=models.CharField(max_length=200, null=True, verbose_name='Passive Skill Target (Evolved)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='hp_1',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='HP (Level 1)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='hp_50',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='HP (Level 50)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='japanese_nakayoshi_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Passive Skill (Japanese)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='japanese_skill_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Skill name (Japanese)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='nakayoshi_skill_effect',
            field=models.CharField(max_length=200, null=True, verbose_name='Passive Skill Effect'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='nakayoshi_skill_target',
            field=models.CharField(max_length=200, null=True, verbose_name='Passive Skill Target'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='nakayoshi_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Passive Skill'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='obtain_method',
            field=models.CharField(max_length=100, null=True, verbose_name='Obtain Method'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='skill_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='Skill comment'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='skill_range',
            field=models.CharField(max_length=300, null=True, verbose_name='Skill range'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='sp_1',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='SP (Level 1)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='sp_50',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='SP (Level 50)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='card',
            name='special_icon',
            field=models.ImageField(upload_to=hoshimori.models.uploadItem(b'c/icon/special'), null=True, verbose_name='Special Icon'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='irous',
            name='guard',
            field=multiselectfield.db.fields.MultiSelectField(default=b'', max_length=100, null=True, verbose_name='Guard', choices=[(0, 'Sword'), (1, 'Spear'), (2, 'Hammer'), (3, 'Gun'), (4, 'Rod'), (5, 'Gunblade'), (6, 'Twin Barrett')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='irous',
            name='strong',
            field=multiselectfield.db.fields.MultiSelectField(default=b'', max_length=100, null=True, verbose_name='Strong', choices=[(0, 'Sword'), (1, 'Spear'), (2, 'Hammer'), (3, 'Gun'), (4, 'Rod'), (5, 'Gunblade'), (6, 'Twin Barrett')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='irous',
            name='weak',
            field=multiselectfield.db.fields.MultiSelectField(default=b'', max_length=100, null=True, verbose_name='Weak', choices=[(0, 'Sword'), (1, 'Spear'), (2, 'Hammer'), (3, 'Gun'), (4, 'Rod'), (5, 'Gunblade'), (6, 'Twin Barrett')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='irousvariation',
            name='image',
            field=models.ImageField(upload_to=hoshimori.models.uploadItem(b'i'), null=True, verbose_name='Image'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='irousvariation',
            name='name',
            field=models.CharField(max_length=50, unique=True, null=True, verbose_name='Irous Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='stage',
            name='easy_stage',
            field=models.OneToOneField(related_name='easy_difficulty', null=True, to='hoshimori.StageDifficulty'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='stage',
            name='hard_stage',
            field=models.OneToOneField(related_name='hard_difficulty', null=True, to='hoshimori.StageDifficulty'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='stage',
            name='normal_stage',
            field=models.OneToOneField(related_name='normal_difficulty', null=True, to='hoshimori.StageDifficulty'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='stagedifficulty',
            name='objectives',
            field=models.CharField(max_length=200, null=True, verbose_name='Objectives'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='CV',
            field=models.CharField(help_text=b'In Japanese characters.', max_length=100, null=True, verbose_name='CV (Japanese)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='catchphrase_1',
            field=models.CharField(max_length=100, null=True, verbose_name='Catchphrase 1'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='catchphrase_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Catchphrase 2'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='destress',
            field=models.CharField(max_length=100, null=True, verbose_name='Destress'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='dream',
            field=models.CharField(max_length=100, null=True, verbose_name='Dream job'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='extra_activity',
            field=models.CharField(max_length=100, null=True, verbose_name='Extracurricular activity'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='family',
            field=models.CharField(max_length=100, null=True, verbose_name='Family members'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='fav_memory',
            field=models.CharField(max_length=100, null=True, verbose_name='Favorite memory'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='fav_phrase',
            field=models.CharField(max_length=100, null=True, verbose_name='Favorite phrase'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='food_dislikes',
            field=models.CharField(max_length=100, null=True, verbose_name='Disliked food'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='food_likes',
            field=models.CharField(max_length=100, null=True, verbose_name='Liked food'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='full_image',
            field=models.ImageField(upload_to=hoshimori.models.uploadItem(b's/full'), null=True, verbose_name='Full Body Image'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='hobby_1',
            field=models.CharField(max_length=100, null=True, verbose_name='Hobby 1'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='hobby_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Hobby 2'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='hobby_3',
            field=models.CharField(max_length=100, null=True, verbose_name='Hobby 3'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='ideal_1',
            field=models.CharField(max_length=100, null=True, verbose_name='Ideal model 1'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='ideal_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Ideal model 2'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='ideal_3',
            field=models.CharField(max_length=100, null=True, verbose_name='Ideal model 3'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='introduction_1',
            field=models.FileField(upload_to=hoshimori.models.uploadItem(b's/voices'), null=True, verbose_name='Introduction 1'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='introduction_2',
            field=models.FileField(upload_to=hoshimori.models.uploadItem(b's/voices'), null=True, verbose_name='Introduction 1'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='pastime',
            field=models.CharField(max_length=100, null=True, verbose_name='Pastime'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='phrase_1',
            field=models.FileField(upload_to=hoshimori.models.uploadItem(b's/voices'), null=True, verbose_name='Phrase 1'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='phrase_2',
            field=models.FileField(upload_to=hoshimori.models.uploadItem(b's/voices'), null=True, verbose_name='Phrase 2'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='romaji_CV',
            field=models.CharField(help_text=b'In romaji.', max_length=100, null=True, verbose_name='CV'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='secret',
            field=models.CharField(max_length=5000, null=True, verbose_name='Secret'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.ImageField(upload_to=hoshimori.models.uploadItem(b's/sign'), null=True, verbose_name='Signature'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='atk_max',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Weapon ATK (Maximum)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='atk_min',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Weapon ATK (Minimum)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='gamma_type',
            field=models.CharField(default=b'', max_length=1, null=True, verbose_name='Gamma Type'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='i_rarity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Rarity', choices=[(0, '\u2605'), (1, '\u2605\u2605'), (2, '\u2605\u2605\u2605'), (3, '\u2605\u2605\u2605\u2605'), (4, '\u2605\u2605\u2605\u2605\u2605')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Price'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='subweapon_effects',
            field=models.CharField(max_length=100, null=True, verbose_name='Subweapon Effects'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='weaponupgrade',
            name='weapon_effects',
            field=models.CharField(max_length=100, null=True, verbose_name='Weapon Effects'),
            preserve_default=True,
        ),
    ]
